#Together not supported yet
#embedder:
# provider: gpt4all
#  config:
#    model: togethercomputer/m2-bert-80M-8k-retrieval

llm:
  provider: together
  config:
    # model: togethercomputer/RedPajama-INCITE-7B-Base
    # prompt: "You act as a helpful and empathic assistant. Always answer in German. "
    model: mistralai/Mixtral-8x7B-Instruct-v0.1
    temperature: 0.0
    max_tokens: 10000
    top_p: 1
    stream: true
    number_documents: 10
    prompt: |
      Always answer in German.
      Think about the solution step by step.
      Only use the following pieces of context to answer the query at the end.
      If you don't know the answer, just say that you don't know, don't try to make up an answer.
      Always answer in German.
      Use bullet points and short sentences.
      
      $context
      
      Query: $query
      
      Helpful Answer:

